/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package grocery;

import static grocery.MainList.grocerytable;
import static grocery.MainList.totalDisplay;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oliverioro_cis12023
 */
public class addItem extends javax.swing.JFrame {
    
    /**
     * Creates new form addItem
     */
    public addItem() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Add Item");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemprice = new javax.swing.JTextField();
        itemdiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemquantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        header.setText("Add Product Item");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Item Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Price:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Discount:");

        itemquantity.setText("1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:");

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        close.setText("Reset");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemdiscount)
                            .addComponent(itemprice)
                            .addComponent(itemname)
                            .addComponent(itemquantity)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Object[] data=getData();
        int row,y;
        groceryclass GC=new groceryclass();
                Double subtotal;
                Double total=0d;
        DefaultTableModel model=(DefaultTableModel)grocerytable.getModel();
        if("Add Product Item".equals(header.getText())){
            for(row=0;row<4&&!"".equals((String)data[row]);row++){}
            if(row==4){
                model.addRow(data);
                
                row=grocerytable.getRowCount();
                for(y=0;y<row;y++){
                    subtotal=GC.getTotalCost((String)grocerytable.getValueAt(y,1), (String)grocerytable.getValueAt(y,3));
                    subtotal=GC.getDiscountedPrice(String.valueOf(subtotal), (String)grocerytable.getValueAt(y,2));
                    grocerytable.setValueAt(String.valueOf(subtotal), y,4);
                }
                for(y=0;y<row;y++){
                    if(grocerytable.getValueAt(y,4)!=null){
                        total+=GC.getTotalPrice((String)grocerytable.getValueAt(y,4));
                    }
                }
                DecimalFormat numberFormat = new DecimalFormat("#.00");
                totalDisplay.setText(String.valueOf(numberFormat.format(total)));
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Some fields are empty!");
            }
        }else if("Edit Product Item".equals(header.getText())){
            row=grocerytable.getSelectedRow();
            int x;
            for(x=0;x<4;x++){
                grocerytable.setValueAt(data[x], row,x);
            }
            row=grocerytable.getRowCount();
                for(y=0;y<row;y++){
                    subtotal=GC.getTotalCost((String)grocerytable.getValueAt(y,1), (String)grocerytable.getValueAt(y,3));
                    System.out.println(subtotal+"\n");
                    subtotal=GC.getDiscountedPrice(String.valueOf(subtotal), (String)grocerytable.getValueAt(y,2));
                    System.out.println(subtotal+"\n");
                    grocerytable.setValueAt(String.valueOf(subtotal), y,4);
                }
                for(y=0;y<row;y++){
                    if(grocerytable.getValueAt(y,4)!=null){
                        total+=GC.getTotalPrice((String)grocerytable.getValueAt(y,4));
                    }
                }
                DecimalFormat numberFormat = new DecimalFormat("#.00");
                totalDisplay.setText(String.valueOf(numberFormat.format(total)));
            dispose();
        }
    }//GEN-LAST:event_addActionPerformed
    public void changeHeader(){
        header.setText("Edit Product Item");
        add.setText("Save");
    }
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        resetData();
    }//GEN-LAST:event_closeActionPerformed
    public void setItemName(String name){
        itemname.setText(name);
    }
    public void setPrice(String price){
        itemprice.setText(price);
    }
    public void setDiscount(String discount){
        itemdiscount.setText(discount);
    }
    public void setQuantity(String qty){
        itemquantity.setText(qty);
    }

    public Object[] getData(){
        Object[] data={
            itemname.getText(),
            itemprice.getText(),
            itemdiscount.getText(),
            itemquantity.getText()
        };
        return data;
    }
    public void resetData(){
        itemname.setText("");
        itemprice.setText("");
        itemdiscount.setText("");
        itemquantity.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton close;
    private javax.swing.JLabel header;
    private javax.swing.JTextField itemdiscount;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextField itemprice;
    private javax.swing.JTextField itemquantity;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
