/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery;

import static grocery.MainList.grocerytable;
import static grocery.MainList.totalDisplay;
import static grocery.MainList.userList;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rjoli
 */
public class fileName extends javax.swing.JFrame {

    /**
     * Creates new form fileName
     */
    public fileName() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Enter name of file");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameFile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a name for the file");

        nameFile.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        String filedir;
        File dir;
        String fileName;
        String itemname,username;
        int qty;
        double salediscount,cost,price;
        DefaultTableModel model=(DefaultTableModel)grocerytable.getModel();
        if("".equals(nameFile.getText())){
            JOptionPane.showMessageDialog(null, "Field is empty!");
        }else{
            dispose();
            fileName=getFileName();
                chooser= new JFileChooser();
                chooser.setCurrentDirectory(new java.io.File("."));
                chooser.setDialogTitle("choosertitle");
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                chooser.setAcceptAllFileFilterUsed(false);
                
                if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    dir=chooser.getSelectedFile();
                   filedir=dir.getAbsolutePath();
                   filedir=filedir+"\\"+fileName+".txt";
                   dir = new File(filedir);
                   try{
                       Class.forName("com.mysql.jdbc.Driver").newInstance();
                        String url = "jdbc:mysql://localhost:8080/grocelist"; 
                        Connection conn = DriverManager.getConnection(url,"root",""); 
                        Statement st = conn.createStatement();
                        
                       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                       Date date=new Date();
                       
                       FileWriter FW=new FileWriter(dir);
                        BufferedWriter BW=new BufferedWriter(FW);
                        username=userList.getText();
                        BW.write("\nLIST BY:: "+userList.getText()+"\n\n");
                        BW.write("\nDATE:: "+formatter.format(date)+"\n\n");
                        BW.write("\nItemName\tSelling Price\tSale Discount\tQuantity\tCost");
                        BW.write("\n_____________________________________________________________________\n");
                        formatter = new SimpleDateFormat("yyyy-MM-dd");
                        for(int i = 0; i < grocerytable.getRowCount(); i++){
                   //loop for jtable column
                        for(int j = 0; j < grocerytable.getColumnCount(); j++){
                           BW.write(grocerytable.getModel().getValueAt(i, j)+"\t\t");
                        }
                            itemname=(String) grocerytable.getValueAt(i, 0);
                            qty=Integer.valueOf((String)grocerytable.getValueAt(i, 3));
                            price=Double.valueOf((String)grocerytable.getValueAt(i, 1));
                            cost=Double.valueOf((String)grocerytable.getValueAt(i, 4));
                            salediscount=Double.valueOf((String)grocerytable.getValueAt(i, 2));
                            String query="INSERT INTO `grocery`(`itemname`, `price`, `salediscount`, `quantity`, `cost`, `username`, `date`) "
                                + "VALUES ('"+itemname+"','"+ price+"','"+ salediscount+"','"+qty+"','"+cost +"','"+ username+"','"+formatter.format(date)+"')";
                            st.executeUpdate(query);
                            BW.write("\n_____________________________________________________________________\n");
                        }
                        //close BufferedWriter
                        BW.write("\n\nTOTAL:: "+totalDisplay.getText());
                        BW.close();
                        //close FileWriter 
                        FW.close();
                        JOptionPane.showMessageDialog(null, "Data Exported");
                   }catch(Exception ex){
                       ex.printStackTrace();
                   }   
                } else {
                  JOptionPane.showMessageDialog(null, "Directory not selected");
                    }
                }
            
    }//GEN-LAST:event_jButton2ActionPerformed
    public String getFileName(){
        return nameFile.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fileName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameFile;
    // End of variables declaration//GEN-END:variables
}
